apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo-service
spec:
  ports:
    - port: 8000 #the port that this service should serve on
      targetPort: 8000
      protocol: TCP
  selector:
    app: todo-service
